export type StopReason =
  | "COMPLETED"
  | "USER_STOP"
  | "WAITING_FOR_USER_INPUT"
  | "PERMISSION_DENIED"
  | "BUDGET_EXHAUSTED"
  | "NO_PROGRESS"
  | "RECOVERED_AFTER_RESTART"
  | "RETRY_EXHAUSTED"
  | "UNRECOVERABLE_ERROR";
